// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent/agent.proto

package agent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobRunStatus int32

const (
	// zero value: no change communicated
	JobRunStatus_STATUS_SAME JobRunStatus = 0
	// job is still starting up
	JobRunStatus_STARTUP JobRunStatus = 1
	// job is in progress
	JobRunStatus_RUNNING JobRunStatus = 2
	// job is no longer running. may have encountered problems and/or
	// been cancelled.
	JobRunStatus_STOPPED JobRunStatus = 3
)

var JobRunStatus_name = map[int32]string{
	0: "STATUS_SAME",
	1: "STARTUP",
	2: "RUNNING",
	3: "STOPPED",
}

var JobRunStatus_value = map[string]int32{
	"STATUS_SAME": 0,
	"STARTUP":     1,
	"RUNNING":     2,
	"STOPPED":     3,
}

func (x JobRunStatus) String() string {
	return proto.EnumName(JobRunStatus_name, int32(x))
}

func (JobRunStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{0}
}

type JobHealthStatus int32

const (
	// zero value: no change communicated
	JobHealthStatus_HEALTH_SAME JobHealthStatus = 0
	// job is currently running with no problems encountered
	JobHealthStatus_OK JobHealthStatus = 1
	// job has encountered problems resulting in degraded performance
	// or quality, but is still running and expected to continue
	JobHealthStatus_DEGRADED JobHealthStatus = 2
	// job has encountered unrecoverable problems and should be
	// treated as failed; will not progress further
	JobHealthStatus_ERROR JobHealthStatus = 3
)

var JobHealthStatus_name = map[int32]string{
	0: "HEALTH_SAME",
	1: "OK",
	2: "DEGRADED",
	3: "ERROR",
}

var JobHealthStatus_value = map[string]int32{
	"HEALTH_SAME": 0,
	"OK":          1,
	"DEGRADED":    2,
	"ERROR":       3,
}

func (x JobHealthStatus) String() string {
	return proto.EnumName(JobHealthStatus_name, int32(x))
}

func (JobHealthStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{1}
}

type JobCancelStatus int32

const (
	// zero value: no change communicated
	JobCancelStatus_CANCEL_SAME JobCancelStatus = 0
	// job has not been asked to be cancelled
	JobCancelStatus_NOCANCEL JobCancelStatus = 1
	// job was requested to be cancelled by user, but this agent
	// refused to cancel; details in outputMessages or errorMessages
	JobCancelStatus_WONTCANCEL JobCancelStatus = 2
	// job was requested to be cancelled by user, and is in process
	// of stopping
	JobCancelStatus_CANCELLING JobCancelStatus = 3
	// job was cancelled by user and has finished stopping
	JobCancelStatus_CANCELLED JobCancelStatus = 4
)

var JobCancelStatus_name = map[int32]string{
	0: "CANCEL_SAME",
	1: "NOCANCEL",
	2: "WONTCANCEL",
	3: "CANCELLING",
	4: "CANCELLED",
}

var JobCancelStatus_value = map[string]int32{
	"CANCEL_SAME": 0,
	"NOCANCEL":    1,
	"WONTCANCEL":  2,
	"CANCELLING":  3,
	"CANCELLED":   4,
}

func (x JobCancelStatus) String() string {
	return proto.EnumName(JobCancelStatus_name, int32(x))
}

func (JobCancelStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{2}
}

// ControllerMsg can consist of one of the available types of
// messages from the main controller to the Agent.
type ControllerMsg struct {
	// Types that are valid to be assigned to Cm:
	//	*ControllerMsg_Describe
	//	*ControllerMsg_Start
	//	*ControllerMsg_Status
	//	*ControllerMsg_Cancel
	Cm                   isControllerMsg_Cm `protobuf_oneof:"cm"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ControllerMsg) Reset()         { *m = ControllerMsg{} }
func (m *ControllerMsg) String() string { return proto.CompactTextString(m) }
func (*ControllerMsg) ProtoMessage()    {}
func (*ControllerMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{0}
}

func (m *ControllerMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerMsg.Unmarshal(m, b)
}
func (m *ControllerMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerMsg.Marshal(b, m, deterministic)
}
func (m *ControllerMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerMsg.Merge(m, src)
}
func (m *ControllerMsg) XXX_Size() int {
	return xxx_messageInfo_ControllerMsg.Size(m)
}
func (m *ControllerMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerMsg proto.InternalMessageInfo

type isControllerMsg_Cm interface {
	isControllerMsg_Cm()
}

type ControllerMsg_Describe struct {
	Describe *DescribeReq `protobuf:"bytes,1,opt,name=describe,proto3,oneof"`
}

type ControllerMsg_Start struct {
	Start *StartReq `protobuf:"bytes,2,opt,name=start,proto3,oneof"`
}

type ControllerMsg_Status struct {
	Status *StatusReq `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type ControllerMsg_Cancel struct {
	Cancel *CancelReq `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

func (*ControllerMsg_Describe) isControllerMsg_Cm() {}

func (*ControllerMsg_Start) isControllerMsg_Cm() {}

func (*ControllerMsg_Status) isControllerMsg_Cm() {}

func (*ControllerMsg_Cancel) isControllerMsg_Cm() {}

func (m *ControllerMsg) GetCm() isControllerMsg_Cm {
	if m != nil {
		return m.Cm
	}
	return nil
}

func (m *ControllerMsg) GetDescribe() *DescribeReq {
	if x, ok := m.GetCm().(*ControllerMsg_Describe); ok {
		return x.Describe
	}
	return nil
}

func (m *ControllerMsg) GetStart() *StartReq {
	if x, ok := m.GetCm().(*ControllerMsg_Start); ok {
		return x.Start
	}
	return nil
}

func (m *ControllerMsg) GetStatus() *StatusReq {
	if x, ok := m.GetCm().(*ControllerMsg_Status); ok {
		return x.Status
	}
	return nil
}

func (m *ControllerMsg) GetCancel() *CancelReq {
	if x, ok := m.GetCm().(*ControllerMsg_Cancel); ok {
		return x.Cancel
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ControllerMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ControllerMsg_Describe)(nil),
		(*ControllerMsg_Start)(nil),
		(*ControllerMsg_Status)(nil),
		(*ControllerMsg_Cancel)(nil),
	}
}

// AgentMsg can consist of one of the available types of messages from the
// Agent to the main controller.
type AgentMsg struct {
	// Types that are valid to be assigned to Am:
	//	*AgentMsg_Describe
	//	*AgentMsg_Status
	Am                   isAgentMsg_Am `protobuf_oneof:"am"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AgentMsg) Reset()         { *m = AgentMsg{} }
func (m *AgentMsg) String() string { return proto.CompactTextString(m) }
func (*AgentMsg) ProtoMessage()    {}
func (*AgentMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{1}
}

func (m *AgentMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMsg.Unmarshal(m, b)
}
func (m *AgentMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMsg.Marshal(b, m, deterministic)
}
func (m *AgentMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMsg.Merge(m, src)
}
func (m *AgentMsg) XXX_Size() int {
	return xxx_messageInfo_AgentMsg.Size(m)
}
func (m *AgentMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMsg proto.InternalMessageInfo

type isAgentMsg_Am interface {
	isAgentMsg_Am()
}

type AgentMsg_Describe struct {
	Describe *DescribeReport `protobuf:"bytes,1,opt,name=describe,proto3,oneof"`
}

type AgentMsg_Status struct {
	Status *StatusReport `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*AgentMsg_Describe) isAgentMsg_Am() {}

func (*AgentMsg_Status) isAgentMsg_Am() {}

func (m *AgentMsg) GetAm() isAgentMsg_Am {
	if m != nil {
		return m.Am
	}
	return nil
}

func (m *AgentMsg) GetDescribe() *DescribeReport {
	if x, ok := m.GetAm().(*AgentMsg_Describe); ok {
		return x.Describe
	}
	return nil
}

func (m *AgentMsg) GetStatus() *StatusReport {
	if x, ok := m.GetAm().(*AgentMsg_Status); ok {
		return x.Status
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AgentMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AgentMsg_Describe)(nil),
		(*AgentMsg_Status)(nil),
	}
}

// DescribeReq requests information about the Agent instance over its
// lifetime (and not information specific to this Job).
type DescribeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeReq) Reset()         { *m = DescribeReq{} }
func (m *DescribeReq) String() string { return proto.CompactTextString(m) }
func (*DescribeReq) ProtoMessage()    {}
func (*DescribeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{2}
}

func (m *DescribeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeReq.Unmarshal(m, b)
}
func (m *DescribeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeReq.Marshal(b, m, deterministic)
}
func (m *DescribeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeReq.Merge(m, src)
}
func (m *DescribeReq) XXX_Size() int {
	return xxx_messageInfo_DescribeReq.Size(m)
}
func (m *DescribeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeReq.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeReq proto.InternalMessageInfo

// JobConfig defines the configuration for a job.
// Relevance of configuration details will depend upon the Agent's
// capabilities.
type JobConfig struct {
	CodeInputs []*JobConfig_CodeInput `protobuf:"bytes,1,rep,name=codeInputs,proto3" json:"codeInputs,omitempty"`
	// codewriter: directory where code can be written
	CodeOutputDir string                 `protobuf:"bytes,2,opt,name=codeOutputDir,proto3" json:"codeOutputDir,omitempty"`
	SpdxInputs    []*JobConfig_SpdxInput `protobuf:"bytes,3,rep,name=spdxInputs,proto3" json:"spdxInputs,omitempty"`
	// spdxwriter: directory path to write one or more output SPDX files
	SpdxOutputDir        string   `protobuf:"bytes,4,opt,name=spdxOutputDir,proto3" json:"spdxOutputDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobConfig) Reset()         { *m = JobConfig{} }
func (m *JobConfig) String() string { return proto.CompactTextString(m) }
func (*JobConfig) ProtoMessage()    {}
func (*JobConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{3}
}

func (m *JobConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobConfig.Unmarshal(m, b)
}
func (m *JobConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobConfig.Marshal(b, m, deterministic)
}
func (m *JobConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobConfig.Merge(m, src)
}
func (m *JobConfig) XXX_Size() int {
	return xxx_messageInfo_JobConfig.Size(m)
}
func (m *JobConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_JobConfig.DiscardUnknown(m)
}

var xxx_messageInfo_JobConfig proto.InternalMessageInfo

func (m *JobConfig) GetCodeInputs() []*JobConfig_CodeInput {
	if m != nil {
		return m.CodeInputs
	}
	return nil
}

func (m *JobConfig) GetCodeOutputDir() string {
	if m != nil {
		return m.CodeOutputDir
	}
	return ""
}

func (m *JobConfig) GetSpdxInputs() []*JobConfig_SpdxInput {
	if m != nil {
		return m.SpdxInputs
	}
	return nil
}

func (m *JobConfig) GetSpdxOutputDir() string {
	if m != nil {
		return m.SpdxOutputDir
	}
	return ""
}

// codereader: code paths under analysis
type JobConfig_CodeInput struct {
	// short description of this code input.
	// "primary" means that it is the primary code under analysis;
	// most codereader agents will expect a "primary" input.
	// otherwise, may be e.g. agent name for the upstream agent that
	// retrieved and placed the code in place.
	// if the Agent is also an spdxreader, then the CodeInput could
	// have a corresponding SpdxInput describing it in further detail.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// paths to directories or files to be analyzed
	Paths                []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobConfig_CodeInput) Reset()         { *m = JobConfig_CodeInput{} }
func (m *JobConfig_CodeInput) String() string { return proto.CompactTextString(m) }
func (*JobConfig_CodeInput) ProtoMessage()    {}
func (*JobConfig_CodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{3, 0}
}

func (m *JobConfig_CodeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobConfig_CodeInput.Unmarshal(m, b)
}
func (m *JobConfig_CodeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobConfig_CodeInput.Marshal(b, m, deterministic)
}
func (m *JobConfig_CodeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobConfig_CodeInput.Merge(m, src)
}
func (m *JobConfig_CodeInput) XXX_Size() int {
	return xxx_messageInfo_JobConfig_CodeInput.Size(m)
}
func (m *JobConfig_CodeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_JobConfig_CodeInput.DiscardUnknown(m)
}

var xxx_messageInfo_JobConfig_CodeInput proto.InternalMessageInfo

func (m *JobConfig_CodeInput) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *JobConfig_CodeInput) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

// spdxreader: paths to multiple earlier SPDX files which may be reused
type JobConfig_SpdxInput struct {
	// short description for source of SPDX file; may be e.g. agent name,
	// "former" for former known good SPDX files; etc.
	// don't try to include too much detail here; the agent can read the
	// SPDX file and get more data if it wants to. this is just meant to
	// give enough info to the agent to decide whether it potentially
	// cares about the file at all.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// paths to SPDX files (or directories containing them) for this source
	Paths                []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobConfig_SpdxInput) Reset()         { *m = JobConfig_SpdxInput{} }
func (m *JobConfig_SpdxInput) String() string { return proto.CompactTextString(m) }
func (*JobConfig_SpdxInput) ProtoMessage()    {}
func (*JobConfig_SpdxInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{3, 1}
}

func (m *JobConfig_SpdxInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobConfig_SpdxInput.Unmarshal(m, b)
}
func (m *JobConfig_SpdxInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobConfig_SpdxInput.Marshal(b, m, deterministic)
}
func (m *JobConfig_SpdxInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobConfig_SpdxInput.Merge(m, src)
}
func (m *JobConfig_SpdxInput) XXX_Size() int {
	return xxx_messageInfo_JobConfig_SpdxInput.Size(m)
}
func (m *JobConfig_SpdxInput) XXX_DiscardUnknown() {
	xxx_messageInfo_JobConfig_SpdxInput.DiscardUnknown(m)
}

var xxx_messageInfo_JobConfig_SpdxInput proto.InternalMessageInfo

func (m *JobConfig_SpdxInput) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *JobConfig_SpdxInput) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

// StartReq requests that a Job be started on this Agent. An Agent should
// respond to this (eventually) by sending a StatusReport.
type StartReq struct {
	// configuration for this job
	Config               *JobConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StartReq) Reset()         { *m = StartReq{} }
func (m *StartReq) String() string { return proto.CompactTextString(m) }
func (*StartReq) ProtoMessage()    {}
func (*StartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{4}
}

func (m *StartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReq.Unmarshal(m, b)
}
func (m *StartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReq.Marshal(b, m, deterministic)
}
func (m *StartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReq.Merge(m, src)
}
func (m *StartReq) XXX_Size() int {
	return xxx_messageInfo_StartReq.Size(m)
}
func (m *StartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartReq proto.InternalMessageInfo

func (m *StartReq) GetConfig() *JobConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

// StatusReq requests that the Agent send a status update message
// about the Job for this connection.
type StatusReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReq) Reset()         { *m = StatusReq{} }
func (m *StatusReq) String() string { return proto.CompactTextString(m) }
func (*StatusReq) ProtoMessage()    {}
func (*StatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{5}
}

func (m *StatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReq.Unmarshal(m, b)
}
func (m *StatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReq.Marshal(b, m, deterministic)
}
func (m *StatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReq.Merge(m, src)
}
func (m *StatusReq) XXX_Size() int {
	return xxx_messageInfo_StatusReq.Size(m)
}
func (m *StatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReq proto.InternalMessageInfo

// CancelReq requests that the Agent cancel the Job for this connection.
// An Agent should respond to this (eventually) by sending a StatusReport.
type CancelReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelReq) Reset()         { *m = CancelReq{} }
func (m *CancelReq) String() string { return proto.CompactTextString(m) }
func (*CancelReq) ProtoMessage()    {}
func (*CancelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{6}
}

func (m *CancelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelReq.Unmarshal(m, b)
}
func (m *CancelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelReq.Marshal(b, m, deterministic)
}
func (m *CancelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelReq.Merge(m, src)
}
func (m *CancelReq) XXX_Size() int {
	return xxx_messageInfo_CancelReq.Size(m)
}
func (m *CancelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelReq proto.InternalMessageInfo

// DescribeReport provides information about the Agent instance over its
// lifetime (and not information specific to this Job).
type DescribeReport struct {
	// the name of this agent, e.g. its unique name within the peridot group
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the type of this agent, which does not need to be unique within the
	// peridot group
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// this agent's configuration on startup, returned as a YAML string.
	// this is not the particular Job's configuration.
	AgentConfig string `protobuf:"bytes,3,opt,name=agentConfig,proto3" json:"agentConfig,omitempty"`
	// this agent's capabilities
	Capabilities         []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeReport) Reset()         { *m = DescribeReport{} }
func (m *DescribeReport) String() string { return proto.CompactTextString(m) }
func (*DescribeReport) ProtoMessage()    {}
func (*DescribeReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{7}
}

func (m *DescribeReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeReport.Unmarshal(m, b)
}
func (m *DescribeReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeReport.Marshal(b, m, deterministic)
}
func (m *DescribeReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeReport.Merge(m, src)
}
func (m *DescribeReport) XXX_Size() int {
	return xxx_messageInfo_DescribeReport.Size(m)
}
func (m *DescribeReport) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeReport.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeReport proto.InternalMessageInfo

func (m *DescribeReport) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DescribeReport) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DescribeReport) GetAgentConfig() string {
	if m != nil {
		return m.AgentConfig
	}
	return ""
}

func (m *DescribeReport) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

// StatusReport provides information about the Job for this connection.
// It should be issued promptly following receipt of a StartReq, StatusReq
// or CancelReq, and may be issued periodically otherwise at the Agent's
// discretion.
type StatusReport struct {
	// is the job running?
	RunStatus JobRunStatus `protobuf:"varint,1,opt,name=runStatus,proto3,enum=agent.JobRunStatus" json:"runStatus,omitempty"`
	// is the job healthy?
	HealthStatus JobHealthStatus `protobuf:"varint,2,opt,name=healthStatus,proto3,enum=agent.JobHealthStatus" json:"healthStatus,omitempty"`
	// was the job requested to be cancelled?
	CancelStatus JobCancelStatus `protobuf:"varint,3,opt,name=cancelStatus,proto3,enum=agent.JobCancelStatus" json:"cancelStatus,omitempty"`
	// time when the job was started, as Unix time
	TimeStarted int64 `protobuf:"varint,4,opt,name=timeStarted,proto3" json:"timeStarted,omitempty"`
	// time when the job stopped running, as Unix time
	TimeFinished int64 `protobuf:"varint,5,opt,name=timeFinished,proto3" json:"timeFinished,omitempty"`
	// logged output, if any. should be short messages; anything
	// lengthy should be separately logged or reported elsewhere
	OutputMessages string `protobuf:"bytes,6,opt,name=outputMessages,proto3" json:"outputMessages,omitempty"`
	// logged errors, if any
	ErrorMessages        string   `protobuf:"bytes,7,opt,name=errorMessages,proto3" json:"errorMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReport) Reset()         { *m = StatusReport{} }
func (m *StatusReport) String() string { return proto.CompactTextString(m) }
func (*StatusReport) ProtoMessage()    {}
func (*StatusReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{8}
}

func (m *StatusReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReport.Unmarshal(m, b)
}
func (m *StatusReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReport.Marshal(b, m, deterministic)
}
func (m *StatusReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReport.Merge(m, src)
}
func (m *StatusReport) XXX_Size() int {
	return xxx_messageInfo_StatusReport.Size(m)
}
func (m *StatusReport) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReport.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReport proto.InternalMessageInfo

func (m *StatusReport) GetRunStatus() JobRunStatus {
	if m != nil {
		return m.RunStatus
	}
	return JobRunStatus_STATUS_SAME
}

func (m *StatusReport) GetHealthStatus() JobHealthStatus {
	if m != nil {
		return m.HealthStatus
	}
	return JobHealthStatus_HEALTH_SAME
}

func (m *StatusReport) GetCancelStatus() JobCancelStatus {
	if m != nil {
		return m.CancelStatus
	}
	return JobCancelStatus_CANCEL_SAME
}

func (m *StatusReport) GetTimeStarted() int64 {
	if m != nil {
		return m.TimeStarted
	}
	return 0
}

func (m *StatusReport) GetTimeFinished() int64 {
	if m != nil {
		return m.TimeFinished
	}
	return 0
}

func (m *StatusReport) GetOutputMessages() string {
	if m != nil {
		return m.OutputMessages
	}
	return ""
}

func (m *StatusReport) GetErrorMessages() string {
	if m != nil {
		return m.ErrorMessages
	}
	return ""
}

func init() {
	proto.RegisterEnum("agent.JobRunStatus", JobRunStatus_name, JobRunStatus_value)
	proto.RegisterEnum("agent.JobHealthStatus", JobHealthStatus_name, JobHealthStatus_value)
	proto.RegisterEnum("agent.JobCancelStatus", JobCancelStatus_name, JobCancelStatus_value)
	proto.RegisterType((*ControllerMsg)(nil), "agent.ControllerMsg")
	proto.RegisterType((*AgentMsg)(nil), "agent.AgentMsg")
	proto.RegisterType((*DescribeReq)(nil), "agent.DescribeReq")
	proto.RegisterType((*JobConfig)(nil), "agent.JobConfig")
	proto.RegisterType((*JobConfig_CodeInput)(nil), "agent.JobConfig.CodeInput")
	proto.RegisterType((*JobConfig_SpdxInput)(nil), "agent.JobConfig.SpdxInput")
	proto.RegisterType((*StartReq)(nil), "agent.StartReq")
	proto.RegisterType((*StatusReq)(nil), "agent.StatusReq")
	proto.RegisterType((*CancelReq)(nil), "agent.CancelReq")
	proto.RegisterType((*DescribeReport)(nil), "agent.DescribeReport")
	proto.RegisterType((*StatusReport)(nil), "agent.StatusReport")
}

func init() { proto.RegisterFile("agent/agent.proto", fileDescriptor_253ddf9934d56132) }

var fileDescriptor_253ddf9934d56132 = []byte{
	// 720 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x4b, 0x6f, 0xd3, 0x4a,
	0x14, 0xc7, 0x6b, 0x3b, 0x49, 0xe3, 0x93, 0x47, 0x7d, 0xe7, 0xf6, 0x56, 0x56, 0x57, 0x95, 0x75,
	0x05, 0x51, 0x24, 0x4a, 0x49, 0x61, 0x41, 0x17, 0x48, 0xc1, 0x71, 0x9b, 0x96, 0x36, 0xa9, 0xc6,
	0xa9, 0x58, 0x56, 0x8e, 0x33, 0x24, 0x96, 0x12, 0xdb, 0xd8, 0x63, 0x01, 0x1b, 0xbe, 0x1d, 0x12,
	0x1b, 0xbe, 0x13, 0x9a, 0x87, 0x1d, 0x3b, 0x15, 0x0b, 0x36, 0x91, 0xcf, 0x7f, 0x7e, 0x67, 0xce,
	0x63, 0x4e, 0x0e, 0xfc, 0xe3, 0x2d, 0x49, 0x48, 0x5f, 0xf2, 0xdf, 0xd3, 0x38, 0x89, 0x68, 0x84,
	0xea, 0xdc, 0xb0, 0x7e, 0x2a, 0xd0, 0xb1, 0xa3, 0x90, 0x26, 0xd1, 0x7a, 0x4d, 0x92, 0xbb, 0x74,
	0x89, 0xce, 0xa0, 0xb9, 0x20, 0xa9, 0x9f, 0x04, 0x73, 0x62, 0x2a, 0x27, 0x4a, 0xaf, 0x35, 0x40,
	0xa7, 0xc2, 0x71, 0x24, 0x65, 0x4c, 0x3e, 0x8f, 0xf7, 0x70, 0x41, 0xa1, 0xe7, 0x50, 0x4f, 0xa9,
	0x97, 0x50, 0x53, 0xe5, 0xf8, 0x81, 0xc4, 0x5d, 0xa6, 0x09, 0x56, 0x9c, 0xa3, 0x3e, 0x34, 0x52,
	0xea, 0xd1, 0x2c, 0x35, 0x35, 0x4e, 0x1a, 0x5b, 0x92, 0x66, 0xa9, 0x40, 0x25, 0xc1, 0x58, 0xdf,
	0x0b, 0x7d, 0xb2, 0x36, 0x6b, 0x15, 0xd6, 0xe6, 0xa2, 0x64, 0x05, 0xf1, 0xbe, 0x06, 0xaa, 0xbf,
	0xb1, 0x28, 0x34, 0x87, 0x0c, 0x61, 0x45, 0x9c, 0x3f, 0x29, 0xe2, 0xbf, 0x27, 0x45, 0xc4, 0x51,
	0x42, 0x2b, 0x75, 0xbc, 0x28, 0xd2, 0x13, 0x85, 0xfc, 0xbb, 0x93, 0x9e, 0x74, 0x90, 0x10, 0x8b,
	0xea, 0x6d, 0xac, 0x0e, 0xb4, 0x4a, 0x7d, 0xb1, 0x7e, 0xa8, 0xa0, 0xdf, 0x44, 0x73, 0x3b, 0x0a,
	0x3f, 0x05, 0x4b, 0x74, 0x01, 0xe0, 0x47, 0x0b, 0x72, 0x1d, 0xc6, 0x19, 0x4d, 0x4d, 0xe5, 0x44,
	0xeb, 0xb5, 0x06, 0xc7, 0xf2, 0xd6, 0x82, 0x3a, 0xb5, 0x73, 0x04, 0x97, 0x68, 0xf4, 0x3f, 0x74,
	0x98, 0x35, 0xcd, 0x68, 0x9c, 0xd1, 0x51, 0x90, 0xf0, 0xa4, 0x74, 0x5c, 0x15, 0x59, 0x84, 0x34,
	0x5e, 0x7c, 0x95, 0x11, 0xb4, 0x3f, 0x44, 0x70, 0x73, 0x04, 0x97, 0x68, 0x16, 0x81, 0x59, 0xdb,
	0x08, 0x35, 0x11, 0xa1, 0x22, 0x1e, 0xbf, 0x05, 0xbd, 0x48, 0x10, 0x1d, 0x41, 0x23, 0x8d, 0xb2,
	0xc4, 0x17, 0x5d, 0xd5, 0xb1, 0xb4, 0xd0, 0x21, 0xd4, 0x63, 0x8f, 0xae, 0x58, 0xe7, 0xb4, 0x9e,
	0x8e, 0x85, 0xc1, 0x5c, 0x8b, 0xc8, 0x7f, 0xe7, 0x6a, 0xbd, 0x86, 0x66, 0x3e, 0x3f, 0xa8, 0x07,
	0x0d, 0x9f, 0xd7, 0x21, 0x9f, 0xd2, 0xd8, 0xad, 0x0f, 0xcb, 0x73, 0xab, 0x05, 0x7a, 0x31, 0x4b,
	0xcc, 0x28, 0x86, 0xc5, 0xfa, 0x0e, 0xdd, 0xea, 0xcb, 0x23, 0x04, 0xb5, 0xd0, 0xdb, 0xe4, 0xd9,
	0xf0, 0x6f, 0xa6, 0xd1, 0x6f, 0x31, 0x91, 0xad, 0xe6, 0xdf, 0xe8, 0x04, 0x5a, 0x3c, 0x9c, 0x08,
	0xc5, 0x27, 0x57, 0xc7, 0x65, 0x09, 0x59, 0xd0, 0xf6, 0xbd, 0xd8, 0x9b, 0x07, 0xeb, 0x80, 0x06,
	0x24, 0x35, 0x6b, 0xbc, 0x90, 0x8a, 0x66, 0xfd, 0x52, 0xa1, 0x5d, 0x9e, 0x23, 0xf4, 0x0a, 0xf4,
	0x24, 0x0b, 0x85, 0xc4, 0x73, 0xe8, 0x16, 0xf3, 0x76, 0x13, 0xcd, 0x71, 0x7e, 0x84, 0xb7, 0x14,
	0xba, 0x80, 0xf6, 0x8a, 0x78, 0x6b, 0xba, 0x72, 0xb7, 0x53, 0xda, 0x1d, 0x1c, 0x6d, 0xbd, 0xc6,
	0xa5, 0x53, 0x5c, 0x61, 0x99, 0xaf, 0xf8, 0xb3, 0xb8, 0xdb, 0x3f, 0x60, 0xc5, 0xd7, 0x2e, 0x9d,
	0xe2, 0x0a, 0xcb, 0x3a, 0x40, 0x83, 0x0d, 0xe1, 0xef, 0x41, 0x16, 0x7c, 0x4a, 0x34, 0x5c, 0x96,
	0x58, 0x07, 0x98, 0x79, 0x19, 0x84, 0x41, 0xba, 0x22, 0x0b, 0xb3, 0xce, 0x91, 0x8a, 0x86, 0x9e,
	0x41, 0x37, 0xe2, 0x43, 0x75, 0x47, 0xd2, 0xd4, 0x5b, 0x92, 0xd4, 0x6c, 0xf0, 0x56, 0xee, 0xa8,
	0x6c, 0x2a, 0x49, 0x92, 0x44, 0x49, 0x81, 0xed, 0x8b, 0xa9, 0xac, 0x88, 0xfd, 0x4b, 0x68, 0x97,
	0xdb, 0x84, 0x0e, 0xa0, 0xe5, 0xce, 0x86, 0xb3, 0x07, 0xf7, 0xd1, 0x1d, 0xde, 0x39, 0xc6, 0x1e,
	0x6a, 0xc1, 0xbe, 0x3b, 0x1b, 0xe2, 0xd9, 0xc3, 0xbd, 0xa1, 0x30, 0x03, 0x3f, 0x4c, 0x26, 0xd7,
	0x93, 0x2b, 0x43, 0x15, 0x27, 0xd3, 0xfb, 0x7b, 0x67, 0x64, 0x68, 0x7d, 0x1b, 0x0e, 0x76, 0x1a,
	0xc7, 0xae, 0x1a, 0x3b, 0xc3, 0xdb, 0xd9, 0x38, 0xbf, 0xaa, 0x01, 0xea, 0xf4, 0x83, 0xa1, 0xa0,
	0x36, 0x34, 0x47, 0xce, 0x15, 0x1e, 0x8e, 0x9c, 0x91, 0xa1, 0x22, 0x1d, 0xea, 0x0e, 0xc6, 0x53,
	0x6c, 0x68, 0xfd, 0x47, 0x7e, 0x49, 0xb9, 0x83, 0xec, 0x12, 0x7b, 0x38, 0xb1, 0x9d, 0xdb, 0xfc,
	0x92, 0x36, 0x34, 0x27, 0x53, 0x21, 0x19, 0x0a, 0xea, 0x02, 0x7c, 0x9c, 0x4e, 0x66, 0xd2, 0x56,
	0x99, 0x2d, 0xbe, 0x6f, 0x59, 0x8e, 0x1a, 0xea, 0x80, 0x2e, 0x6d, 0x67, 0x64, 0xd4, 0x06, 0xef,
	0xa0, 0xce, 0x57, 0x1b, 0x7a, 0x03, 0x8d, 0x09, 0xf9, 0x72, 0x13, 0xcd, 0xd1, 0x61, 0xbe, 0x0f,
	0xcb, 0xcb, 0xfb, 0x38, 0xdf, 0xbd, 0xf9, 0x22, 0xb4, 0xf6, 0x7a, 0xca, 0x99, 0x32, 0x6f, 0xf0,
	0x9d, 0x7f, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xed, 0xd7, 0xc0, 0xd5, 0x08, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	// NewJob is the only RPC endpoint that an Agent provides. It
	// is a bidirectional streaming RPC that enables the Controller to
	// send messages to the Agent, and vice versa. It will remain open
	// during the lifetime of a given Job and its early termination
	// means that the Job should be treated as failed.
	NewJob(ctx context.Context, opts ...grpc.CallOption) (Agent_NewJobClient, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) NewJob(ctx context.Context, opts ...grpc.CallOption) (Agent_NewJobClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Agent_serviceDesc.Streams[0], "/agent.Agent/NewJob", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentNewJobClient{stream}
	return x, nil
}

type Agent_NewJobClient interface {
	Send(*ControllerMsg) error
	Recv() (*AgentMsg, error)
	grpc.ClientStream
}

type agentNewJobClient struct {
	grpc.ClientStream
}

func (x *agentNewJobClient) Send(m *ControllerMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentNewJobClient) Recv() (*AgentMsg, error) {
	m := new(AgentMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	// NewJob is the only RPC endpoint that an Agent provides. It
	// is a bidirectional streaming RPC that enables the Controller to
	// send messages to the Agent, and vice versa. It will remain open
	// during the lifetime of a given Job and its early termination
	// means that the Job should be treated as failed.
	NewJob(Agent_NewJobServer) error
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_NewJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServer).NewJob(&agentNewJobServer{stream})
}

type Agent_NewJobServer interface {
	Send(*AgentMsg) error
	Recv() (*ControllerMsg, error)
	grpc.ServerStream
}

type agentNewJobServer struct {
	grpc.ServerStream
}

func (x *agentNewJobServer) Send(m *AgentMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentNewJobServer) Recv() (*ControllerMsg, error) {
	m := new(ControllerMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NewJob",
			Handler:       _Agent_NewJob_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent/agent.proto",
}
